# workflows do not have same permissions across forks pr. from same repo (branch to branch)
# labeler cant write across forks https://github.com/actions/labeler/issues/12
name: Labeler
on: [pull_request]

jobs:
  label:
    runs-on: windows-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
